plugins {
    id 'java'
    id 'eclipse'
    id 'application'
}
 
application {
    mainClass = 'hello.HelloWorld'
}
 
repositories {
    mavenCentral()
}
 
jar {
    archiveBaseName.set('jb-hello-world')
    archiveVersion.set('0.1.0')
}
 
java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
 
dependencies {
    implementation 'joda-time:joda-time:2.2'
    testImplementation 'junit:junit:4.12'
}
